### ISSUE TITLE
Update Cordova

### ISSUE THREAD

**Issue by Maikell84** [IngoAlbers/no_salad_friends#10]
When building the software there is a warning message:

```
Using this version of Cordova with older version of cordova-android is being deprecated. Consider upgrading to cordova-android@5.0.0 or newer.
```

We should update the cordova version.

**Comment by IngoAlbers** [comment]
Version of cordova and the cordova-android is not defined in the project, but part of the local development setup. 
It should be a recent version. If you get deprecation warnings you should consider updating. 

If the update causes any problems with the application, please create a new issue.
