### ISSUE TITLE
Add colorblind mode

### ISSUE THREAD

**Issue by IngoAlbers** [IngoAlbers/no_salad_friends#7]
Colorblind people might have problems with the distinction between buttons and background. We need to use colors that are easily recognizable and powerful for the visually impaired.

**Comment by IngoAlbers** [comment]
Internal and external quality control by colorblind and people with regular vision concluded that the apps color scheme is appropriate and easily distinguishable.

**Comment by tieneguasa** [comment]
That's a very nice thing, Ingo! 😉
